= Luiz Henrique A. Mello
Luiz Mello <lhamello@gmail.com>
Kismet Chameleon <kismet@asciidoctor.org>
:revnumber: 1.0 
:revdate: Nov 2021
:icons: font
:linkattrs:
:sectanchors:
:sectlink:
:experimental:
:source-language: asciidoc
:includedir: _includes

// Refs
:link-resume: http://lhamello.github.io/resume
:link-linkedin: https://www.linkedin.com/in/lhamello
:link-twitter: https://twitter.com/lhamello
:link-home: https://goo.gl/maps/NpRTv
:link-github: https://github.com/lhamello

// Other links
:link-procergs: http://www.procergs.rs.gov.br/
:link-digitel: http://www.digitel.com.br/pt/home/default.asp
:link-pucrs: https://www.pucrs.br/
:link-unisc: https://www.unisc.br/

ifeval::["{backend}" == "html5"]
icon:file-pdf-o[] Read this resume {link-resume}/index.pdf[in PDF here, role="external", window="_blank"]. +
endif::[]

ifeval::["{backend}" == "pdf"]
icon:html5[] Read this resume {link-resume}/index.html[in HTML5 here, role="external", window="_blank"]. +
endif::[]

[discrete]
== Systems Analyst / Developer

****

I'm a Analyst/Software Engineer/Developer who works on Java enterprise application using technologies such as JavaEE, CDI and Angular. +

I have a bachelor degree in {link-resume}/#_education[Computer Science] and I work with software development since 2008. +

I'm currently working as a team leader, scrum master, systems analyst and developer at {link-procergs}[PROCERGS^]. The team that I am part of, and that I lead, is responsible for developing new features for the vehicle area system of the state traffic department. +


****

== Main interests

* JavaEE / CDI
* Spring
* SpringBoot
* Agile methodologies
* Testing
* Continuos Delivery
* SOA / Microservices
* Docker and containers

== Personal details

`Name:` Luiz Henrique Araujo Mello +
`Social Media:` icon:linkedin[link={link-linkedin}, role="external", window="_blank", alt="@lhamello"] / icon:github[link={link-github}, role="external", window="_blank", alt="@lhamello"] / icon:twitter[link={link-twitter}, role="external", window="_blank", alt="@lhamello"] +
`Location:` {link-home}["Porto Alegre/RS, Brazil", role="external", window="_blank"] +
`Email`: lhamello@gmail.com +
`Phone:` +55 51 99325-3558


== Professional Experience

=== Systems Analyst / Developer at PROCERGS

icon:calendar[title="Period"] _August 2011 to Now (On going)_ +
icon:group[title="Employee"] {link-procergs}[PROCERGS - Cia. de Processamento de Dados do Rio Grande do Sul, role="external", window="_blank"] +

--
[horizontal]
Position:: *Team leader - Scrum Master - Systems Analist - Developer* +
--

* Create and maintain JavaEE-based solutions for several Rio Grande do Sul state secretariats
* Manage demands directly with external customers
* Creating user stories
* Acting as a Scrum Master and a team leader
* Organize and manage team backlog
* Migrating legacy systems in Cobol to Java applications

==== Used technologies

* JavaEE 6/7 stack (mainly EJB, CDI, JaxRS/RestEasy/Jersey, JSF, JPA/Hibernate)
* Primefaces / Richfaces
* JSF
* Cucumber / Selenium / Junit (tests)
* Swagger (REST API)
* JBoss EAP 6/7 (application server)
* Maven
* Jasper Reports
* Artifactory
* Jenkins
* Sonar
* OracleDB/Postgres
* Redmine/TFS
* CVS/SVN/GIT
* Docker


=== Java Developer at Digitel

icon:calendar[title="Period"] _December 2008 to August 2011_ +
icon:group[title="Employee"] {link-digitel}[DIGITEL, role="external", window="_blank"] +

--
[horizontal]
Position:: *Java Developer* +
--

* Modular software development using JAVA (J2EE and Swing), JBoss and PostgreSQL platform, in client-server architecture
* Active participation in the search for improvements and new technologies to improve the developed software
* Creation of a new software standard for the product line worked

==== Used technologies

* Java
* Swing
* JBoss
* PostgreSQL



== Technical Skills

Languages and Specifications:: Java SE 7/8, JSON, YAML, Swagger

Application Servers:: *JBoss EAP 6/7*, Bea Weblogic and Apache Tomcat/Tomee

Frameworks and Libraries:: *Java EE* (JSF, JPA, EJB, CDI, JAX-RS, Servlet), J2EE, http://primefaces.org[Primefaces^].

OS:: Windows

Databases:: Oracle, PostgreSQL and HSQLDB/H2

Software Engineering:: OOP, DevOps, Design Patterns, Unit Testing, Integration Testing, BDD, Continuous Delivery

Tools:: Eclipse, Netbeans, Maven, Redmine, Subversion, Git, Asciidoctor, Jenkins, Sonar, Artifactory, Visual Studio Code.

ADLM:: AzureDevops

== Languages Skills

* Portuguese : Native
* English : Intermediate

== Education

=== Specialist degree: Software engineering with an emphasis on government solutions
* University: Universidade de Santa Cruz do Sul ({link-pucrs}[UNISC, role="external", window="_blank"])
* icon:calendar[title="Period"] _2014-2016_ - *Concluded*

=== Bachelor’s degree: Bachelor in Computer Science
* University: Pontifícia Universidade Católica do Rio Grande do Sul ({link-pucrs}[PUCRS, role="external", window="_blank"])
* icon:calendar[title="Period"] _2006-2010_ - *Concluded*
